language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-26
    - build-tools-26.0.2

before_script:
  - chmod +x gradlew
  
script:
  - ./gradlew assembleRelease
